### ISSUE TITLE
数据库脚本在哪

### ISSUE THREAD

**Issue by gitzhangliang** [yingshang/banruo#14]
数据库脚本在哪

**Comment by yingshang** [comment]
cd /opt/banruo 
python3 manage.py makemigrations 
python3 manage.py migrate

在config.json设置好mysql连接，运行上面命令

**Comment by gitzhangliang** [comment]
能提供一个用户名 和 密码不  我在数据库手动插入的  不行

**Comment by gitzhangliang** [comment]
第一次看python  不太懂里面逻辑

**Comment by gitzhangliang** [comment]
这个系统在windows下怎么配置  比如fortify的配置  能提供一份window下教程吗

**Comment by yingshang** [comment]
设置超级用户  用下面命令创建用户就可以登录，在windows在config.json修改fortify路径
python3 manage.py createsuperuser
