### ISSUE TITLE
现在没有继续更新吗

### ISSUE THREAD

**Issue by barkosHuang** [yingshang/banruo#19]
请问现在还有继续更新到新的版本吗

**Comment by yingshang** [comment]
你想要什么功能，有些功能没有更新上去

**Comment by barkosHuang** [comment]
待写部分，请问源代码防泄漏平台（待写）会继续更新吗

**Comment by yingshang** [comment]
这个没有更新，不造轮子，网上已经有了：https://github.com/VKSRC/Github-Monitor
