### ISSUE TITLE
在哪里可以看到项目漏洞详情

### ISSUE THREAD

**Issue by xufengnian** [yingshang/banruo#2]
大佬你好，我这边下载了源码以后，结合自己的linux版fortify可以实现项目代码扫描，也能显示漏洞类型和饼状图，但是项目情况里一直没有看到什么地方可以点进去查看扫描漏洞的详情和问题代码部分，请问是什么情况呢？

**Comment by yingshang** [comment]
有没有具体的详情

**Comment by xufengnian** [comment]
已经找到地方，非常抱歉，项目很赞！

**Comment by yingshang** [comment]
谢谢！
