### ISSUE TITLE
搭建手册有么

### ISSUE THREAD

**Issue by devsecops-SRC** [yingshang/banruo#7]
搭建手册有么

**Comment by yingshang** [comment]
用centos7，按照dockerfile里面的内容本地安装就行

**Comment by kingsec666** [comment]
您微信   这个项目问题咨询

**Comment by yingshang** [comment]
你可以在这里咨询

**Comment by hack2012** [comment]
Fortify linux版的安装路径有要求不？

**Comment by yingshang** [comment]
> Fortify linux版的安装路径有要求不？

没有，假如你要放在其他目录，你只需去config.json那里修改路径就行

**Comment by hack2012** [comment]
Step 4/19 : COPY fortify_linux /opt/fortify_linux
lstat fortify_linux: no such file or directory

是要先在本机安装fortify?  我已经安装了，在/opt/fortify_linux/ 
一直搞不懂你这个docker file

**Comment by yingshang** [comment]
> Step 4/19 : COPY fortify_linux /opt/fortify_linux
> lstat fortify_linux: no such file or directory
> 
> 是要先在本机安装fortify? 我已经安装了，在/opt/fortify_linux/
> 一直搞不懂你这个docker file

这只是一个fortify的目录名字，你可以在config.json那里修改，我这里只不过想突出我使用linux的版本，下面就是fortify的审计和生成报告的二进制，链接他们

`RUN chmod 777 -R /opt/fortify_linux/ && ln -s /opt/fortify_linux/bin/sourceanalyzer /usr/local/bin/sourceanalyzer && ln -s /opt/fortify_linux/bin/ReportGenerator /usr/local/bin/ReportGenerator
`

**Comment by hack2012** [comment]
> > Step 4/19 : COPY fortify_linux /opt/fortify_linux
> > lstat fortify_linux: no such file or directory
> > 是要先在本机安装fortify? 我已经安装了，在/opt/fortify_linux/
> > 一直搞不懂你这个docker file
> 
> 这只是一个fortify的目录名字，你可以在config.json那里修改，我这里只不过想突出我使用linux的版本，下面就是fortify的审计和生成报告的二进制，链接他们
> 
> `RUN chmod 777 -R /opt/fortify_linux/ && ln -s /opt/fortify_linux/bin/sourceanalyzer /usr/local/bin/sourceanalyzer && ln -s /opt/fortify_linux/bin/ReportGenerator /usr/local/bin/ReportGenerator `

我安装后，把fortify复制到dockerfile目录下，这一步才搞定。

**Comment by yingshang** [comment]
> > > Step 4/19 : COPY fortify_linux /opt/fortify_linux
> > > lstat fortify_linux: no such file or directory
> > > 是要先在本机安装fortify? 我已经安装了，在/opt/fortify_linux/
> > > 一直搞不懂你这个docker file
> > 
> > 
> > 这只是一个fortify的目录名字，你可以在config.json那里修改，我这里只不过想突出我使用linux的版本，下面就是fortify的审计和生成报告的二进制，链接他们
> > `RUN chmod 777 -R /opt/fortify_linux/ && ln -s /opt/fortify_linux/bin/sourceanalyzer /usr/local/bin/sourceanalyzer && ln -s /opt/fortify_linux/bin/ReportGenerator /usr/local/bin/ReportGenerator `
> 
> 我安装后，把fortify复制到dockerfile目录下，这一步才搞定。

对啊，你需要在dockerfile的目录下将fortify的目录复制过去=-=我这边没有提供fortify啊
