### ISSUE TITLE
Docker安装报错

### ISSUE THREAD

**Issue by hack2012** [yingshang/banruo#8]
![docker](https://user-images.githubusercontent.com/3817100/71388480-8385e800-2633-11ea-8755-b9cbf745c0d5.png)
安装报错了，这是什么情况？
还有你的docker安装没有优化pip源，安装是相当慢呀。

**Comment by yingshang** [comment]
什么错误？安装pip慢是不是网速问题

**Comment by hack2012** [comment]
报错请看上面的图片。。请帮忙看看这个。
pip慢是因为你没有修改pip源导致的问题。pip慢这个问题我解决了。

**Comment by yingshang** [comment]
你用的是centos7+python3.5?

**Comment by hack2012** [comment]
我用的docker安装呀，这个是docker安装过程报错。
![docker](https://user-images.githubusercontent.com/3817100/71389149-26d7fc80-2636-11ea-9139-5756a50cb903.png)

**Comment by yingshang** [comment]
稍等，我复现一下

**Comment by yingshang** [comment]
我知道了什么问题，我的dockerfile没有mysql数据库，我设置了外连，在config.json文件里面，我现在弄两个版本的dockerfile吧

**Comment by yingshang** [comment]
你要不要设置外连？因为dockerfile生成的centos7的systemctl启动权限不够
`
[root@148288cb7242 /]# systemctl 
Failed to get D-Bus connection: Operation not permitted
`
设置外连只需在config.json设置mysql的host，账号，密码就行

**Comment by hack2012** [comment]
你的dockerfile不是基于ubuntu的吗？ 建议你修改一下dockerfile 直接安装个mysql服务也行，就不用别人另外再搭建个mysql 然后外连了。

**Comment by yingshang** [comment]
不是，那个是旧版，新版看github文档，因为我升级了mitmproxy库，然后这个库在Ubuntu安装很麻烦，来到Centos7之后，发现安装很顺利，就用7了。测试的话，我等会上传个demo，但是说到生产环境的话，我觉得外连好用一点

**Comment by hack2012** [comment]
好的。。多谢，之前没有看到这个安装步骤，是才加的？

> 安装步骤
第一步，你需要将fortify的linux版本复制到和dockerfile同一个目录下(如果想要改名字改路径的，可以到config.json改)
第二步，设置一台mysql服务器，可以是自己虚拟机上面的MySQL，mysql创建一个数据库，我的是banruo,然后将mysql的连接信息在config.json修改
第三步，运行dockerfile就可以进行连接查看。

**Comment by yingshang** [comment]
对啊，都怪我太懒了，没写上去，不好意思=-=

**Comment by yingshang** [comment]
刚刚测试一下，dockerfile有点问题，等我弄好，我告诉你

**Comment by hack2012** [comment]
嗯，我也是研究了好半天才搞定那个fortify那一步。
你这个项目搞好，还是不错的。期待你完善一下docker安装。
搞安全的都有点懒。

**Comment by yingshang** [comment]
好了，搞好了，demo你可以看这个视频https://github.com/yingshang/banruo/blob/master/run.mkv
dockerfile那里还有一个run.sh脚本做docker运行用的

**Comment by hack2012** [comment]
国内访问github真他MD的慢，累呀。 在docker里面下载不是一般的慢呀。

**Comment by yingshang** [comment]
=-=国外vps构建完成，打包再用daocloud加速源下载回来

**Comment by hack2012** [comment]
> =-=国外vps构建完成，打包再用daocloud加速源下载回来

多谢指导，谢谢兄弟。
